Reading from the files and separating participants who completed the tasks from the rest.

In [1]:
import json
import numpy as np
import scipy.stats as stats
import statistics
from statsmodels.sandbox.stats.multicomp import multipletests

In [2]:
def nasa_string_to_int(nasa_string):
    sn= nasa_string.replace('[','').replace(']','').split(',')
    ntr1 = [int(y) for y in sn]
    return ntr1

In [3]:
# Opening JSON file
f = open('output2.json')

In [4]:
data = json.load(f)

In [5]:
# for x in data['data']:
#     keys = x.keys()
#     print(keys)
#     values = x.values()
#     print(values)
#     print(x['completed'])
    

In [6]:
completed_participants=[]
for x in data['data']:
    if(x['completed']):
        completed_participants.append(x['mturk_id'])
# print(completed_participants)
        

In [7]:
f = open('output1.json')

In [8]:
jsonpmodel = json.load(f)

In [9]:
# for x in data['data']:
#     keys = x.keys()
#     print(keys)
#     print('\n')
#     values = x.values()
#     print(values)

In [10]:
completed_p_models=[]
for x in jsonpmodel['data']:
#     print(x['sequence_type'])
    m=x['mturk_id']
    if(m in completed_participants):
        completed_p_models.append(x)
        

In [11]:
filename='completedparticipants.json'
with open(filename, 'w') as json_file:
    json.dump(completed_p_models, json_file, 
                        indent=4,  
                        separators=(',',': '))

In [12]:
c_file=open(filename)
c_p=json.load(c_file)

In [13]:
# for x in c_p:
#     print(x['mturk_id'])

completedparticipants.json is the file that includes data of all participants who completed the task 
and c_p is the json varible of the file



In [14]:
# ----------------Experiment Sequences---------------------------

# N : first nbackn difficulty (H/E)

# Q : first Questionaire (1: NASA-TLX and 2: MRQ)

# S : SakeDifficulty(H/E)

# _________________________________________________________________________
# seq_number/Progress | 1.n1 | 2.s | 3.q1| 4.q2|5.n2 | 6.s |7.q1 |8.q2 |
# _________________________________________________________________________
#          1          |  E   | E   |  1  |  2  |  H  |  E  |  1  |  2  |
#          2          |  E   | E   |  2  |  1  |  H  |  E  |  2  |  1  |
#          3          |  H   | E   |  1  |  2  |  E  |  E  |  1  |  2  |
#          4          |  H   | E   |  2  |  1  |  E  |  E  |  2  |  1  |
#          5          |  E   | H   |  1  |  2  |  H  |  H  |  1  |  2  |
#          6          |  E   | H   |  2  |  1  |  H  |  H  |  2  |  1  |
#          7          |  H   | H   |  1  |  2  |  E  |  H  |  1  |  2  |
#          8          |  H   | H   |  2  |  1  |  E  |  H  |  2  |  1  |
# ________________________________________________________________________


In [15]:
 #  sequence type /progress matrix 
E_n = 1; # easy nbackn
H_n = 3; # hard nbackn
E_s = 500;  # easy sak in ms
H_s = 1000; #hard sak in ms
seq_prog = [
    [E_n, E_s, 1, 2, H_n, E_s, 1, 2],
    [E_n, E_s, 2, 1, H_n, E_s, 2, 1],
    [H_n, E_s, 1, 2, E_n, E_s, 1, 2],
    [H_n, E_s, 2, 1, E_n, E_s, 2, 1],
    [E_n, H_s, 1, 2, H_n, H_s, 1, 2],
    [E_n, H_s, 2, 1, H_n, H_s, 2, 1],
    [H_n, H_s, 1, 2, E_n, H_s, 1, 2],
    [H_n, H_s, 2, 1, E_n, H_s, 2, 1]
];

conEX : Easy NBACKN----
conHX : Hard NBACKN----
conXE: Easy SAK----
conXH: Hard SAK

In [16]:
nasa_1_t_array=[]
nasa_2_t_array=[]
nasa_1_r_array=[]
nasa_2_r_array=[]

seq_type_array=[]

mrq_1_array=[]
mrq_2_array=[]

mrq_conEH_array=[]
mrq_conHH_array=[]
mrq_conEE_array=[]
mrq_conHE_array=[]

nasa_r_conEH_array=[]
nasa_r_conHH_array=[]
nasa_r_conEE_array=[]
nasa_r_conHE_array=[]

nasa_t_conEH_array=[]
nasa_t_conHH_array=[]
nasa_t_conEE_array=[]
nasa_t_conHE_array=[]



for x in c_p:
    st= x['sequence_type']
    seq_type_array.append(st)
    
    ntr1= nasa_string_to_int(x['nasa_1_r'][0])
    ntr2= nasa_string_to_int(x['nasa_2_r'][0])
    ntt1= nasa_string_to_int(x['nasa_1_t'][0])
    ntt2= nasa_string_to_int(x['nasa_2_t'][0])

    
    
    nasa_1_r_array.append(ntr1)
    nasa_1_t_array.append(ntt1)
    nasa_2_r_array.append(ntr2)
    nasa_2_t_array.append(ntt2)
    
    
    
    
    s=x['mrq_1'][0].replace('"','').replace('[',"").replace(']',"").split(',')
    mrq1 = [int(y) for y in s]
    mrq1.pop()
    
    
    s=x['mrq_2'][0].replace('"','').replace('[',"").replace(']',"").split(',')
    mrq2 = [int(y) for y in s]
    mrq2.pop()
    
    mrq_1_array.append(mrq1)
    mrq_2_array.append(mrq2)
    
    if(st==1 or st==2):
        mrq_conEE_array.append(mrq1)
        mrq_conHE_array.append(mrq2)
        nasa_r_conEE_array.append(ntr1)
        nasa_r_conHE_array.append(ntr2)
        nasa_t_conEE_array.append(ntt1)
        nasa_t_conHE_array.append(ntt2)
       
    if(st==3 or st==4):
        mrq_conHE_array.append(mrq1)
        mrq_conEE_array.append(mrq2)
        nasa_r_conHE_array.append(ntr1)
        nasa_r_conEE_array.append(ntr2)
        nasa_t_conHE_array.append(ntt1)
        nasa_t_conEE_array.append(ntt2)
        
    if(st==5 or st==6):
        mrq_conEH_array.append(mrq1)
        mrq_conHH_array.append(mrq2)
        nasa_r_conEH_array.append(ntr1)
        nasa_r_conHH_array.append(ntr2)
        nasa_t_conEH_array.append(ntt1)
        nasa_t_conHH_array.append(ntt2)
   
    if(st==7 or st==8):
        mrq_conHH_array.append(mrq1)
        mrq_conEH_array.append(mrq2)
        nasa_r_conHH_array.append(ntr1)
        nasa_r_conEH_array.append(ntr2)
        nasa_t_conHH_array.append(ntt1)
        nasa_t_conEH_array.append(ntt2)
        


<b>Starting the analysis from here:

<hr style="width:100%;text-align:left;margin-left:0">

<b>Analysis 1: Paired t-test to see effect of first task on second one 

-----------------------------------------------------------------------------------------------------------------------

<b>First Part for MRQ:</b>

r_mrq_pttest, p_mrq_pttest for each dimension separately and for r_mrq_avg,p_mrq_avg for total average as the last element.

p_mrq_pttest_adjusted is the adjusted p-values after boneferroni

In [17]:
mrqEX= mrq_conEE_array + mrq_conEH_array

In [18]:
mrqHX= mrq_conHE_array + mrq_conHH_array

In [19]:
mrqEX=np.array(mrqEX)

In [20]:
mrqHX=np.array(mrqHX)

In [21]:
r_mrq_pttest=[]
p_mrq_pttest=[]

for i in range(len(mrqHX[0])):
    r,p = stats.ttest_rel(mrqHX[:,i], mrqEX[:,i])
    r_mrq_pttest.append(r)
    p_mrq_pttest.append(p)
    
mrqHX_avg_array= np.mean(mrqHX, axis=1)
mrqEX_avg_array= np.mean(mrqEX, axis=1)
r_mrq_avg,p_mrq_avg = stats.ttest_rel(mrqHX_avg_array,mrqEX_avg_array)

r_mrq_pttest.append(r_mrq_avg)
p_mrq_pttest.append(p_mrq_avg)

In [22]:
p_mrq_pttest_adjusted = multipletests(p_mrq_pttest, alpha=0.05, method='bonferroni')

In [23]:
p_mrq_pttest_adjusted

(array([False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False]),
 array([1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 0.91805869, 1.        ,
        0.95111004, 0.80106367, 1.        ,        nan, 1.        ,
        1.        , 1.        , 1.        ]),
 0.002845571131556368,
 0.002777777777777778)

In [24]:
p_mrq_pttest

[0.4961015555245206,
 0.8722883630840339,
 0.34343639613791355,
 0.16785065605707492,
 0.34343639613791355,
 0.13818475535118327,
 0.811373655241246,
 0.27887299924891695,
 0.051003260706950763,
 0.16785065605707492,
 0.05283944651707043,
 0.044503537305576386,
 0.11076492156976729,
 nan,
 0.1038881310621017,
 0.27887299924891695,
 0.34343639613791355,
 0.07281555477214813]

<b>Second Part for NASA-TLX:</b>

r_nasa_pttest, p_nasa_pttest for each dimension separately and for r_nasa_avg,p_nasa_avg for total average as the last element.

p_nasa_pttest_adjusted is the adjusted p-values after boneferroni

In [25]:
nasaEX= nasa_r_conEE_array + nasa_r_conEH_array

In [26]:
nasaHX= nasa_r_conHE_array + nasa_r_conHH_array

In [27]:
nasaEX=np.array(nasaEX)

In [28]:
nasaHX=np.array(nasaHX)

In [29]:
r_nasa_pttest=[]
p_nasa_pttest=[]

for i in range(len(nasaHX[0])):
    r,p = stats.ttest_rel(nasaHX[:,i], nasaEX[:,i])
    r_nasa_pttest.append(r)
    p_nasa_pttest.append(p)
    
nasaHX_avg_array= np.mean(nasaHX, axis=1)
nasaEX_avg_array= np.mean(nasaEX, axis=1)
r_nasa_avg,p_nasa_avg = stats.ttest_rel(nasaHX_avg_array,nasaEX_avg_array)

r_nasa_pttest.append(r_nasa_avg)
p_nasa_pttest.append(p_nasa_avg)

In [30]:
p_nasa_pttest_adjusted = multipletests(p_nasa_pttest, alpha=0.05, method='bonferroni')

In [31]:
p_nasa_pttest

[0.5425520719530796,
 0.7640411601083001,
 0.3041151886808649,
 0.02729189815631593,
 0.24892626365964873,
 0.09320637160539949,
 0.19342205960333203]

In [32]:
p_nasa_pttest_adjusted

(array([False, False, False, False, False, False, False]),
 array([1.        , 1.        , 1.        , 0.19104329, 1.        ,
        0.6524446 , 1.        ]),
 0.007300831979014655,
 0.0071428571428571435)

<hr style="width:100%;text-align:left;margin-left:0">

<b> Analysis 2: two-sample t-test to see effect of one-key text entry task difficulty on questionaires

<b>First Part for MRQ:</b>

r_mrq_pttest, p_mrq_pttest for each dimension separately and for r_mrq_avg,p_mrq_avg for total average as the last element.

p_mrq_pttest_adjusted is the adjusted p-values after boneferroni

In [66]:
mrqXE= mrq_conEE_array + mrq_conHE_array

In [67]:
mrqXH= mrq_conEH_array + mrq_conHH_array

In [68]:
mrqEX=np.array(mrqXE) #just did not want the notation. do not confuse EX and XE 

In [69]:
mrqHX=np.array(mrqXH) #just did not want the notation. do not confuse EX and XE 

In [70]:
r_mrq_pttest=[]
p_mrq_pttest=[]

for i in range(len(mrqHX[0])):
    r,p = stats.ttest_ind(mrqHX[:,i], mrqEX[:,i], equal_var=True)
    r_mrq_pttest.append(r)
    p_mrq_pttest.append(p)
    
mrqHX_avg_array= np.mean(mrqHX, axis=1)
mrqEX_avg_array= np.mean(mrqEX, axis=1)
r_mrq_avg,p_mrq_avg = stats.ttest_ind(mrqHX_avg_array,mrqEX_avg_array, equal_var=True)

r_mrq_pttest.append(r_mrq_avg)
p_mrq_pttest.append(p_mrq_avg)

In [71]:
p_mrq_pttest_adjusted = multipletests(p_mrq_pttest, alpha=0.05, method='bonferroni')

In [72]:
p_mrq_pttest_adjusted

(array([False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False]),
 array([1.        , 1.        , 1.        , 1.        , 1.        ,
        0.62690115, 0.89819393, 0.20015485, 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        0.25067513, 1.        , 1.        ]),
 0.002845571131556368,
 0.002777777777777778)

In [73]:
p_mrq_pttest

[0.6318736384548027,
 0.9026623766357643,
 0.6409598012304204,
 0.4311073910501848,
 0.5579282415825825,
 0.034827841408376914,
 0.049899662558439035,
 0.011119714090839545,
 0.529329051766497,
 0.06972056607214441,
 0.09931472610364016,
 0.8734872283133776,
 0.6102531520664984,
 0.08558567459485754,
 0.5579282415825825,
 0.013926395886806338,
 0.6409598012304204,
 0.8840305869851582]

<b>Second Part for NASA-TLX:</b>

r_nasa_pttest, p_nasa_pttest for each dimension separately and for r_nasa_avg,p_nasa_avg for total average as the last element.

p_nasa_pttest_adjusted is the adjusted p-values after boneferroni

In [25]:
nasaXE= nasa_r_conEE_array + nasa_r_conHE_array

In [26]:
nasaXH= nasa_r_conHH_array + nasa_r_conEH_array

In [27]:
nasaEX=np.array(nasaXE) #just did not want the notation. do not confuse EX and XE 

In [28]:
nasaHX=np.array(nasaXH) #just did not want the notation. do not confuse EX and XE 

In [74]:
r_nasa_pttest=[]
p_nasa_pttest=[]

for i in range(len(nasaHX[0])):
    r,p = stats.ttest_ind(nasaHX[:,i], nasaEX[:,i], equal_var=True)
    r_nasa_pttest.append(r)
    p_nasa_pttest.append(p)
    
nasaHX_avg_array= np.mean(nasaHX, axis=1)
nasaEX_avg_array= np.mean(nasaEX, axis=1)
r_nasa_avg,p_nasa_avg = stats.ttest_ind(nasaHX_avg_array,nasaEX_avg_array, equal_var=True)

r_nasa_pttest.append(r_nasa_avg)
p_nasa_pttest.append(p_nasa_avg)

In [75]:
p_nasa_pttest_adjusted = multipletests(p_nasa_pttest, alpha=0.05, method='bonferroni')

In [76]:
p_nasa_pttest

[0.6720370037895823,
 0.9504218052817074,
 0.4434037362384208,
 0.26748150967768614,
 0.5096740994535836,
 0.2560954728537678,
 0.48743210933945214]

In [77]:
p_nasa_pttest_adjusted

(array([False, False, False, False, False, False, False]),
 array([1., 1., 1., 1., 1., 1., 1.]),
 0.007300831979014655,
 0.0071428571428571435)

<hr style="width:100%;text-align:left;margin-left:0">